name: C/C++ CI

on: [push]

jobs:
  build-native:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "*nix: Install Qt"
      uses: jurplel/install-qt-action@v2
    - name: Build
      run: |
        qmake
        make
    - name: "*nix: Stash"
      if: matrix.os != 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: GbaWadUtil-${{ matrix.os }}
        path: GbaWadUtil

